### ISSUE TITLE
Write array groupBy function and paste it in this issue

### ISSUE THREAD

**Issue by stacon** [samioan/react-poker-app#24]

**Comment by samioan** [comment]
const groupBy = (arr, fn) => {
  let count = {};
  arr.forEach((x) => {
    count[x] = (count[x] || 0) + 1;
  });
  return count;
};

**Comment by samioan** [comment]
const groupBy = (arr, fn) => {
  let count = {};
  let newerArr = [];

  for (let x = 0; x < arr.length; x++) {
    let newArr = [];

    if (fn(arr[x])) {
      newArr.push(arr[x]);
      newerArr.push(...newArr);
      count[fn(arr[x])] = newerArr.flat();
    } 

  }

  return count
};

//Best I could figure out so far

**Comment by samioan** [comment]
const groupBy = (arr, fn) => {
 
  let count = {};
  arr.forEach((x) => {
    (count[fn(x)] = (count[fn(x)] || [])).push(x)
  });

  return count;
};

This one actually works finally!

**Comment by samioan** [comment]
const groupBy = (arr, itr) => {
  let count = {};
  arr.forEach((x) => {
    (count[typeof itr === "function" ? itr(x) : x[itr]] =
      count[typeof itr === "function" ? itr(x) : x[itr]] || []).push(x);
  });

  return count;
};

added functionality: GroupBy can now accept functional and primitive iteratees
