### ISSUE TITLE
Design UI

### ISSUE THREAD

**Issue by stacon** [samioan/react-poker-app#7]
- Use a wireframing tool or whatever suits ui to design the ui. We will discuss changes and we will commit on its implementation Later.
- Deposit mocks of your proposal here.

After we have concluded, implementation and CSS will take place

**Comment by johnnthough** [comment]
Hello , Do you need a UI designer?

**Comment by stacon** [comment]
Hello! No this is project is for acaaademic purposes. Thanks for your offer.

**Comment by stacon** [comment]
Abandon
